version: "3.9"

services:
  open-school-java-aop-postgres:
    image: postgres:16
    container_name: open_school_java_aop_postgres
    environment:
      POSTGRES_DB: "aop"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  open-school-java-aop-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open_school_java_aop_app
    depends_on:
      - open-school-java-aop-postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://open-school-java-aop-postgres:5432/aop
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update